[package]
name = "lumendeck"
version = "0.2.47"
description = "Wallpaper-driven RGB lighting, live wallpapers and screen stickers for Windows."
edition = "2021"

[lib]
name = "lumendeck_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
auto-launch = "0.5"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-log = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
openrgb = "0.1.2"
tokio = { version = "1", features = ["full"] }
dirs = "6"
url = "2"
notify = "8"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
base64 = "0.22"
png = "0.17"
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
env_logger = "0.11"
wasapi = "0.16"
tauri-plugin-global-shortcut = "2"
rust-i18n = "4.2.4"
tauri-plugin-window-state = "2.5.0"
zip = "2"
sha2 = "0.10"
sysinfo = "0.39"

[target.'cfg(windows)'.dependencies]
windows-future = "0.3"
windows-core = "0.62"
windows = { version = "0.62", features = [
  "Foundation",
  "Devices_Enumeration",
  "Devices_Lights",
  "UI",
  "Media",
  "Media_Control",
  "Storage",
  "Storage_Streams",
  "System_UserProfile",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_Controls",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Globalization",
  "Win32_Graphics_Dwm",
  "Win32_System_Power",
  "Win32_System_SystemInformation",
  "Win32_System_WindowsProgramming",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_Storage_FileSystem",
  "Win32_Storage_Xps",
  "Win32_Storage_Packaging_Appx",
  "Win32_System_Com",
  "Win32_Media_Audio",
  "Win32_Media_Audio_Endpoints",
  "Win32_System_Registry",
  "Win32_Security",
] }
